config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/programs' => 'programs#index'
  get '/programs/:id' => 'programs#show', as: :program
  get '/match' => 'programs#match', as: :match

end

app/models/program.rb
class Program < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_global_search_variable

  def set_global_search_variable
    @q = Program.search(params[:q])
  end
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show]

  # GET /programs
  # GET /programs.json
  def index
    @search = Program.search(params[:q])
    @programs = @search.result.order(:program_name)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end
  
  def match
   @matches = @q.result.limit(3)
  end

  # GET /programs/new
  #def new
  #  @program = Program.new
  #end

  # GET /programs/1/edit
  # def edit
  # end

  # POST /programs
  # POST /programs.json
  # def create
  #  @program = Program.new(program_params)

  #  respond_to do |format|
  #    if @program.save
  #      format.html { redirect_to @program, notice: 'Program was successfully created.' }
  #      format.json { render :show, status: :created, location: @program }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @program.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  #def update
  #  respond_to do |format|
  #    if @program.update(program_params)
  #      format.html { redirect_to @program, notice: 'Program was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @program }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @program.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /programs/1
  # DELETE /programs/1.json
  #def destroy
  #  @program.destroy
  #  respond_to do |format|
  #    format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params[:program]
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "DC ReEngagement Center"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_matchform.html.erb
<!-- Match Form -->
<%= search_form_for @q, url: match_path, html: { method: :get } do |f| %>
      <%= f.label :program_name_cont %>
      <%= f.text_field :program_name_cont %>
      <%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<div id="navbar-full">
<div id="navbar">
<% if yield(:title) == "DC ReEngagement Center" %>
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
<% else %>
<nav class="navbar navbar-default" role="navigation">
<% end %>
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Virtual REC", root_path, :class => "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar navbar-nav navbar-right">
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Search for Programs", programs_path %></li>
                    <li><button type="button" class="btn btn-info navbar-btn btn-fill btn-round" data-toggle="modal" data-target="#myModal">Connect With Us</button></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        
        <!-- /.container-fluid -->
    </div>
    </nav>

</div>
</div>

    
<!-- Contact Form Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Connect With Us</h4>
          </div>
          <div class="modal-body">
            <div class="text-center">
            <h4>Fill out the form below and we'll get in contact with you!</h4>
            </div>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="First Name and Last Name">
                <label for="exampleInputPassword1">Phone Number or Email</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Phone Number or Email">
                
                <h4>Reason for connecting</h4>
                <label><input type="checkbox"> Enroll in a school or program</label></br>
                <label><input type="checkbox"> Partner with the ReEngagement Center</label></br>
                <label><input type="checkbox"> Other</label></br>
              </div>
            </form>  
          </div>
          <div class="modal-footer">
            <div class="left-side">
              <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
            </div>
            <div class="divider"></div>
            <div class="right-side">
              <button type="button" class="btn btn-info btn-simple">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<% provide(:title, "Programs") %>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-offset-3 col-md-6">
        <h4>We found <span class="text-success"><%= @programs.count %></span> Program(s)</h4>
      </div>
      <div class="col-md-3">
        <%= link_to "Clear Filters", programs_path, :class => "navbar-right" %>
      </div>
    </div>
  </div>
  <div class="row row-offcanvas row-offcanvas-left">
    
    <!-- Sidebar Filters -->
    <div class="col-md-3 col-sm-6 sidebar-offcanvas" id="sidebar" role="navigation"> 
      
      <div class="panel panel-default">
      <div class="panel-body">
        <%= search_form_for @search do |f| %>
          <div class="form-group">
          <%= f.submit "Apply Filters", class: "btn btn-default col-md-12" %>
          <div class="col-md-12"><hr></div>
          <%= f.search_field :program_name_cont, class: "form-control", placeholder: "Search Programs by Name" %>
          </br>
          <%= f.search_field :max_age_gteq, class: "form-control", placeholder: "Student Age" %>
          <hr>
          <p>Secondary Credentials Offered</p>
          <div class="col-md-12">
          <%= f.check_box :credential_hs_diploma_true %>
          <%= f.label :credential_hs_diploma_true, "High School Diploma" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :credential_ged_true %>
          <%= f.label :credential_ged_true, "GED" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :credential_nedp_true %>
          <%= f.label :credential_nedp_true, "NEDP" %>
          </div>
         
          <p>Additional Program Offerings</p>
          <div class="col-md-12">
          <%= f.check_box :class_english_language_true %>
          <%= f.label :class_english_language_true, "English Classes" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :class_workforce_readiness_true %>
          <%= f.label :class_workforce_readiness_true, "Workforce Readiness" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :class_job_training_true %>
          <%= f.label :class_job_training_true, "Career Training" %>
          </div>
          <a class="btn btn-sm btn-simple" role="button" data-toggle="collapse" href="#collapseWorkforce" aria-expanded="false" aria-controls="collapseWorkforce">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> More Career Options
          </a>
          <div class="collapse" id="collapseWorkforce">
            <div class="col-md-12">
            <%= f.check_box :class_construction_true %>
            <%= f.label :class_construction_true, "Construction" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_barbering_true %>
            <%= f.label :class_barbering_true, "Barbering" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_cosmetology_true %>
            <%= f.label :class_cosmetology_true, "Cosmetology" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_childcare_true %>
            <%= f.label :class_childcare_true, "Childcare (CDA)" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_medical_true %>
            <%= f.label :class_medical_true, "Medical Professional" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_culinary_true %>
            <%= f.label :class_culinary_true, "Culinary Arts" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_construction_true %>
            <%= f.label :class_construction_true, "Construction" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_computer_true %>
            <%= f.label :class_computer_true, "Computers/IT" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :class_hvac_true %>
            <%= f.label :class_hvac_true, "HVAC Technician" %>
            </div>
            <div class="col-md-12">
            <%= f.check_box :rec_automotive_technology_true %>
            <%= f.label :rec_automotive_technology_true, "Automotive Technology" %>
            </div>
          </div>
          
          <p>Additional Supports and Services</p>
          <div class="col-md-12">
          <%= f.check_box :rec_childcare_true %>
          <%= f.label :rec_childcare_true, "Childcare Provided" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_spanish_instruction_true %>
          <%= f.label :rec_spanish_instruction_true, "Bilingual Instruction" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_residential_program_true %>
          <%= f.label :rec_residential_program_true, "Residential Program" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_night_classes_true %>
          <%= f.label :rec_night_classes_true, "Night Classes" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_online_courses_true %>
          <%= f.label :rec_online_courses_true, "Online Courses" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_meals_true %>
          <%= f.label :rec_meals_true, "Meals Provided" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_stipend_true %>
          <%= f.label :rec_stipend_true, "Student Stipend" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_job_placement_true %>
          <%= f.label :rec_job_placement_true, "Job Placement" %>
          </div>
          <div class="col-md-12">
          <%= f.check_box :rec_postsec_placement_true %>
          <%= f.label :rec_postsec_placement_true, "Post Secondary Placement" %>
          </div>
          </div>
        <% end %>
      </div>
      </div> <!-- End of Panel Body -->      
    </div> <!-- End of Sidebar Filters -->
    
    <!-- Programs Results Table -->
    <div class="col-md-9">
      <div class="col-md-12 col-sm-12">
      <button type="button" class="btn btn-default btn-fill btn-round visible-xs visible-sm" data-toggle="offcanvas" data-target=".sidbar-nav">Filters</button>
      </div>
      
      <% if @programs.count == 0 %>
      <div class="row">
      <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <h4>Sorry. No Results :(</h4>
        </div>
      </div>
      </div>
      </div>
      <% end %>
      
      <div class="row">
      <div class="col-md-12">
      
          <div class="list-group">
            <% @programs.each do |program| %>
              <% if program.site_status == "Not Updated" %>
              
              <div class="list-group-item disabled">
              <h4 class="list-group-item-heading"><%= program.program_name %></h4>
              <div class="list-group-item-text">
              <p></p><%= program.program_description.truncate(200) %></p>
              <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= program.address %></br>
              <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= program.phone_number %></p>
              </div>
              </div>
               
              <% end %>
            
              <% if program.site_status != "Not Updated" %>
              <%= link_to program, :class => "list-group-item" do %>
              <h4 class="list-group-item-heading"><%= program.program_name %></h4>
              <% if program.accepting_applications == "t" %><p><span class="label label-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Enrolling Now</span></p><% end %>
              <% if program.accepting_applications == "f" %><p><span class="label label-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Not Enrolling</span></p><% end %>
              <div class="list-group-item-text">
              <p></p><%= program.program_description.truncate(200) %></p>
              <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= program.address %></br>
              <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= program.phone_number %></p>
              </div>
              <% end %>  
              <% end %>
            <% end %>
          </div>
          
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <!-- will paginate links -->
        </div>
      </div>
      </div>

        
      </div> <!-- End of Main Section -->
    </div>
  </div>
</div>
</div>

app/views/programs/index.js.erb
<% js = escape_javascript(
  render(partial: 'students/list', locals: { students: @students })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/programs/match.html.erb
<% provide(:title, "Your Matches") %>

<div class="container">
<div class="row">
<h1 class="text-center">Check Out These Programs!</h1>
<p class="text-center">Based on your answers, here are a few programs that might be a good fit.</p>
</div>
</div>

<div class="container">
  <div class="row">
    <% @matches.each do |program| %>
    <div class="marketing col-lg-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= program.program_name %></h3>
        </div>
        <div class="panel-body">
           <p><%= program.program_description.truncate(150) %></p>
            <hr>
            <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= program.address %></br>
            <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= program.phone_number %></p>
            <hr>
            <div class="text-center"><%= link_to "View More Details", program, class: "btn btn-default" %></div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h5 class="text-center">Can't find what you're looking for?</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center"><%= link_to 'Explore All Programs', programs_path, class: "btn btn-warning btn-fill" %></div>
    <br>
  </div>
</div>
<hr>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<% provide(:title, @program.program_name) %>
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p><span class="glyphicon glyphicon-home" aria-hidden="true"></span> / <%= link_to "Programs", programs_path %> / <%= @program.program_name %></p>    
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= @program.program_name %></h3>
        <hr>
        <% if @program.accepting_applications == "t" %><h5><span class="label label-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Enrolling Now</h5><% end %>
        <% if @program.accepting_applications == "f" %><h5><span class="label label-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Not Enrolling</h5><% end %>
        <% if @program.site_status == "Not Updated" %><h5><span class="label label-default"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Out of Date Information</h5><% end %>
        <p>Application Deadline: </p>
        <p>Program Hours: <%= @program.program_start_time %>-<%= @program.program_end_time %></p>
        </br>
        <p><%= @program.program_description %></p>
        
        <hr>
        <div class="col-md-3">
          <h5>Requirements</h5>
        </div>
        <div class="col-md-9">
          
          <ul>
            <% if @program.req_dc_resident == "t" %>
            <li>Washington, DC Resident</li>
            <% end %>
            <% if @program.min_age != nil %>
            <li>Minimum Age: <%= @program.min_age %></li>
            <% end %>
            <% if @program.max_age != nil %>
            <li>Maximum Age: <%= @program.max_age %></li>
            <% end %>
            <% if @program.req_drug_test == "t" %>
            <li>Drug Testing</li>
            <% end %>
            <% if @program.req_vaccination == "t" %>
            <li>Vaccinations</li>
            <% end %>
            <% if @program.math_CASAS_score != nil %>
            <li>Minimum Math CASAS Score: <%= @program.math_CASAS_score %></li>
            <% end %>
            <% if @program.reading_CASAS_score != nil %>
            <li>Minimum Reading CASAS Score: <%= @program.reading_CASAS_score %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-md-12"><hr></div>
        <div class="col-md-3">
          <h5>Credentials and Programs</h5>
        </div>
        <div class="col-md-9">
          <p>
          <ul>
            <% if @program.credential_nedp == "t" %>
            <li>National External Diploma Program (NEDP)</li>
            <% end %>
            <% if @program.credential_ged == "t" %>
            <li>GED (General Educational Development)</li>
            <% end %>
            <% if @program.credential_hs_diploma == "t" %>
            <li>High School Diploma</li>
            <% end %>
            <% if @program.credential_servsafe == "t" %>
            <li>Serv Safe</li>
            <% end %>
            <% if @program.credential_ic3 == "t" %>
            <li>Digital Literacy Certificate IC3</li>
            <% end %>
            <% if @program.class_hs_diploma == "t" %>
            <li>English Basic Education (Math and Reading)</li>
            <% end %>
            <% if @program.rec_spanish_instruction == "t" %>
            <li>Bilingual Instruction - Spanish</li>
            <% end %>
            <% if @program.class_english_language == "t" %>
            <li>English as a Second Language</li>
            <% end %>
            <% if @program.class_computer_literacy == "t" %>
            <li>Computer Literacy</li>
            <% end %>
            <% if @program.class_workforce_readiness == "t" %>
            <li>Workforce Readiness Training</li>
            <% end %>
            <% if @program.class_barbering == "t" %>
            <li>Barbering Classes</li>
            <% end %>
            <% if @program.class_cosmetology == "t" %>
            <li>Cosmetology Classes</li>
            <% end %>
            <% if @program.class_computer == "t" %>
            <li>Computer/Information Technology Classes</li>
            <% end %>
            <% if @program.class_hvac == "t" %>
            <li>Technician Classes (HVAC)</li>
            <% end %>
            <% if @program.class_medical == "t" %>
            <li>Medical Services Classes</li>
            <% end %>
            <% if @program.class_construction == "t" %>
            <li>Construction Training</li>
            <% end %>
          </ul>
          </p>
        </div>
        
        <div class="col-md-12"><hr></div>
        <div class="col-md-3">
          <h5>Additional Supports and Services</h5>
        </div>
        <div class="col-md-9">
          <ul>
            <% if @program.rec_project_based_learning == "t" %>
            <li>Project Based Learning</li>
            <% end %>
            <% if @program.rec_dual_enrollment == "t" %>
            <li>Dual College Enrollment</li>
            <% end %>
            <% if @program.rec_online_courses == "t" %>
            <li>Online Courses</li>
            <% end %>
            <% if @program.rec_internships == "t" %>
            <li>Internships/On Job Training</li>
            <% end %>
            <% if @program.rec_night_classes == "t" %>
            <li>Night Classes Offered</li>
            <% end %>
            <% if @program.rec_childcare == "t" %>
            <li>Childcare</li>
            <% end %>
            <% if @program.rec_childcare_subsidy == "t" %>
            <li>Childcare Subsidy</li>
            <% end %>
            <% if @program.rec_parenting_support == "t" %>
            <li>Parenting Support</li>
            <% end %>
            <% if @program.rec_independent_living == "t" %>
            <li>Independent Living</li>
            <% end %>
            <% if @program.rec_housing_emergency_shelter == "t" %>
            <li>Housing/Emergency Shelter</li>
            <% end %>
            <% if @program.rec_case_management == "t" %>
            <li>Case Management</li>
            <% end %>
            <% if @program.rec_stipend == "t" %>
            <li>Student Stipend</li>
            <% end %>
            <% if @program.rec_onsite_accomodations == "t" %>
            <li>On-site Accomodations</li>
            <% end %>
            <% if @program.rec_mental_health_services == "t" %>
            <li>Mental Health Services</li>
            <% end %>
            <% if @program.rec_meals == "t" %>
            <li>Food Provided</li>
            <% end %>
            <% if @program.rec_alumni_support == "t" %>
            <li>Alumni Support</li>
            <% end %>
            <% if @program.rec_food_bank == "t" %>
            <li>Food Bank</li>
            <% end %>
          </ul>
        </div>
      </div>
      </div>
  </div>

  <div class="col-md-4"> <!-- Side Program Info Panel -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Program Information</h3>
      </div>
      <div class="panel-body">
        <div class="map-container"><div id="map"></div></div>
        
        <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= @program.address %></p>
        <p><span class="glyphicon glyphicon-time" aria-hidden="true"></span> <%= @program.building_open_time %>-<%= @program.building_close_time %></p>
        <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= @program.phone_number %></p>
        <p><span class="glyphicon glyphicon-globe" aria-hidden="true"></span> <%= link_to @program.website_url, @program.website_url %></p>
        
      </div>
    </div>
  </div>
    
  </div>
</div>


<script>
var map;
function initMap() {
  var myLatLng = {lat: <%= @program.address_latitude %>, lng: <%= @program.address_longitude %>};
        
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: myLatLng
  });
  
  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: '<%= @program.program_name %>'
  });
};

marker.setMap(map);
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpTc_dX23-YA81gEEceAPRNlf2VLQi6BI&callback=initMap" async defer></script>

app/views/static_pages/home.html.erb
<% provide(:title, "DC ReEngagement Center") %>

<div class="container-fluid home-hero">
    <div class="row">
      <div class="col-md-offset-2 col-md-8 home-hero-textbox">
        <h1>Let's help you get back on track.</h1>
        <h3>This website is a one-stop resource for District residents of all ages who want to get back on track with their plans to pursue a secondary education credential and a career pathway.</h3>
        <h5><div class="btn btn-info" data-toggle="modal" data-target="#videoModal"><span class="glyphicon glyphicon-play" aria-hidden="true"></span> Watch Video</div>
        <div class="btn btn-info btn-fill" data-toggle="modal" data-target="#matchModal"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find a Program Now</div></h5>
      </div>
    </div>
</div>

<!-- Video Modal -->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <br>
          </div>
          <div class="modal-body">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe id="introvideo" src="https://www.youtube.com/embed/2ih0iH1KIMo" allowscriptaccess frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="modal-footer">
            <div class="text-center">
              <h5><div class="btn btn-info btn-fill btn-lg" data-toggle="modal" data-target="#matchModal"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find a Program Now</div></h5>
              
            </div>
          </div>
        </div>
      </div>
    </div>
    
<!-- Match Form -->
    <div class="modal fade" id="matchModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <br>
          </div>
          <div class="modal-body">
            <h5>Answer the questions below to find programs in Washington, DC that help students attain a high school credential and much more.</h5>
            <hr>
            <h5>How Old Are You?</h5>
            <input type="number" class="form-control" id="exampleInputPassword1" placeholder="Age">
            <h5>What Are Your Academic Goals?</h5>
            <div class="checkbox">
              <label><input type="checkbox"> High School Credential or Equivalent</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Career Training</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Learn English</label>
            </div>
            <h5>Additional Services/Offerings</h5>
            <div class="checkbox">
              <label><input type="checkbox"> Childcare Provided</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Housing Provided</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Night Classes</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Job Placement</label>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Post Secondary Placement</label>
            </div>
          </div>
          <div class="modal-footer">
            <div class="left-side">
              <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
            </div>
            <div class="divider"></div>
            <div class="right-side">
              <%= link_to "Submit", match_path, :class => "btn btn-info btn-simple" %>
            </div>
          </div>
        </div>
      </div>
    </div>